### ISSUE TITLE
linux qt如何更换tileset？

### ISSUE THREAD

**Issue by mttbx** [SunnyEric/NetHack-cn#3]
如题。

**Comment by SunnyYuer** [comment]
把编译后安装目录的nhtiles.bmp替换了试试

**Comment by mttbx** [comment]
那tileset的大小不一样咋办

**Comment by SunnyYuer** [comment]
你没有试怎么知道不行（你试一下嘛），16 * 16，32 * 32，48 * 48都支持的

**Comment by mttbx** [comment]
谢谢，确实有用。还有一点小问题，Qt的设置和游戏选项的设置无法记忆到下一个游戏；还有就是开局选人的时候有的时候阵营无法选择，需要多点几下其他按钮之后才可以选择（比如女武神有时选择不了秩序阵营），有解决办法吗？

**Comment by mttbx** [comment]
试了一下编译tty的版本，只要在hint里用linux就行了，编译完有点问题，就是开局选择人物种族等的时候快捷键无法使用，修改win/tty/wintty.c 中的setup_rolemenu，setup_racemenu，setup_gendmenu，setup_algnmenu函数，把this_ch=...改为this_cn='a'+i;即可，具体还没有完全测试，但是感觉可以玩。

**Comment by SunnyYuer** [comment]
tty版本还行，我没有仔细测过，不知道会不会有什么隐藏bug
