### ISSUE TITLE
老哥可否帮忙

### ISSUE THREAD

**Issue by nidhoggfgg** [SunnyEric/NetHack-cn#4]
我将nethack移植到了termux，但是我想汉化它，3.6.2的版本，老哥可否帮忙?
另外老哥你汉化貌似有部分错误

**Comment by SunnyYuer** [comment]
要3.6.2的汉化版本，需要从上游合并，我可能没这个时间。
但我可以先帮你弄3.6.1的汉化版本。

**Comment by nidhoggfgg** [comment]
ok，对了，老哥可以修复一下3.6.1的汉化版么，选人物那个界面乱码

**Comment by SunnyYuer** [comment]
乱码有很多种原因。能详细说下你的编译步骤吗？

**Comment by nidhoggfgg** [comment]
我是在termux内make的
因为我要移植到termux
首先我cd到nethack目录
执行sh sys/unix/setup.sh sys/unix/hints/linux
报错lex command not found
因为在termux内flex默认是lex补丁包，于是我exec了lex，最后make成功了，并且成功地完美运行了nethack3.6.2
于是我按照一样的方法make了你的汉化版，却出现了人物选择界面乱码的现象

**Comment by SunnyYuer** [comment]
从你的编译方法来看，应该是属于编译linux版的。但在linux系统里编译后，终端里不会乱码。应该是termux的显示问题。这个东西我没有折腾过，，我也不知道该咋办。

**Comment by nidhoggfgg** [comment]
我大概知道了，应该可以使用srceen指定一下编码为GBK，多谢了

**Comment by SunnyYuer** [comment]
请问你的问题解决了吗？

**Comment by nidhoggfgg** [comment]
唉……没搞了，还是有乱码……

**Comment by nidhoggfgg** [comment]
老哥秀啊，汉化的东西不少

**Comment by nidhoggfgg** [comment]
老哥，你汉化问题耶。我仔细阅读源码发现，人物选择其实基于第一个字符
选择人物时它会获取第一个字符作为选择标志，如果是元音字母开头还会是，an xxx(一个xxx)

**Comment by SunnyYuer** [comment]
（别老哥老哥的-_-）你是只有人物选择界面是乱码，其他界面是好的吗？最好来个截图
目前支持的只有linux和windows编译。按理说你编linux版，不会运行你读的那段代码的。你编译其他版本的，可能就会出现那些问题。

**Comment by nidhoggfgg** [comment]
如图
http://img02.sogoucdn.com/app/a/100520146/ce8928a57f3eb0f8939bc0eb0ec5c9f0

**Comment by SunnyYuer** [comment]
扩展命令里选version我看一下

**Comment by nidhoggfgg** [comment]
你说的哪个扩展命令?我这里有自编译3.6.2，貌似和3.6.1冲突

**Comment by SunnyYuer** [comment]
就是按#，然后选version

**Comment by nidhoggfgg** [comment]
http://img01.sogoucdn.com/app/a/100520146/8a84323df7d52110ae48dd42ea5a87c6

**Comment by SunnyYuer** [comment]
我知道了。我之前以为你是全部乱码。linux-tty版本的话，确实选择则人物界面会乱码。我都没有去支持，我只支持了linux-qt版本。
要改的话其实也很简单，你会的话，你修改一下就行了。

**Comment by nidhoggfgg** [comment]
我已经改了，感谢老哥汉化了那么多

**Comment by SunnyYuer** [comment]
话说干嘛不直接玩安卓版呢？

**Comment by nidhoggfgg** [comment]
因为……我在移植游戏到termux，这个东西妙啊

**Comment by nidhoggfgg** [comment]
我不是为了玩游戏而编译游戏，而是为了更多人玩
