### ISSUE TITLE
有针对/nethack/doc/guidebook.txt的汉化吗

### ISSUE THREAD

**Issue by builtins** [SunnyEric/NetHack-cn#5]
我想弄到一个guidebook.txt的汉化版本，或者guidebook.pdf也行
有没有这样的汉化？

**Comment by SunnyYuer** [comment]
https://pan.baidu.com/s/1jGCUMA6
3.4.3版本的，没有新版的。
声明一下这是别人的成果，我懒得汉化这个。

**Comment by builtins** [comment]
谢谢
